#+TITLE:     Beamer-Präsentationen mit dem CD der TU Dresden
#+AUTHOR:    Tobias Schlemmer
#+EMAIL:     Tobias.Schlemmer@tu-dresden.de
#+DATE:      @latex:7.\,5.~2012@
#+DESCRIPTION:
#+KEYWORDS:
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+OPTIONS:   H:3 num:t toc:t \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:nil todo:t pri:nil tags:f
#+INFOJS_OPT: view:nil toc:nil ltoc:t mouse:underline buttons:0 path:http://orgmode.org/org-info.js
#+LINK_UP:   
#+LINK_HOME: 
#+XSLT:
#+startup: beamer
#+startup: indent
#+LaTeX_CLASS: beamer
#+LaTeX_CLASS_OPTIONS: [presentation,t]
#+BEAMER_FRAME_LEVEL: 3
#+LATEX_HEADER_EXTRA: \pdfmapfile{+tud}%
#+LATEX_HEADER_EXTRA: \pdfmapfile{+tudscr}%
#+LATEX_HEDAER_EXTRA: %
#+LATEX_HEDAER_EXTRA: %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
#+LATEX_HEDAER_EXTRA: %                                                                %
#+LATEX_HEDAER_EXTRA: % Vereinfachte Organisation von Präsentationen mit               %
#+LATEX_HEDAER_EXTRA: % Emacs und org-mode                                             %
#+LATEX_HEDAER_EXTRA: %                                                                %
#+LATEX_HEDAER_EXTRA: %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
#+LATEX_HEDAER_EXTRA: %                                                                %
#+LATEX_HEDAER_EXTRA: % Automatisch erstellt mit Hilfe von Emacs und org-mode          %
#+LATEX_HEDAER_EXTRA: % Die .org-Datei kann mit Emacs und installiertem or -Paket      %
#+LATEX_HEDAER_EXTRA: % bearbeitet und nach LaTeX exportiert werden.                   %
#+LATEX_HEDAER_EXTRA: % Der Export ist über die Tastenkombination C-C e l P möglich    %
#+LATEX_HEDAER_EXTRA: %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
#+LATEX_HEDAER_EXTRA: %
#+LATEX_HEADER_EXTRA: \usepackage{amsmath}
#+LATEX_HEADER_EXTRA: \usepackage{uniinput}
#+LATEX_HEADER_EXTRA: \usepackage{amsfonts}
#+LATEX_HEADER_EXTRA: \usepackage{tikz}
#+LATEX_HEADER_EXTRA: \usepackage[ngerman]{babel}
#+LATEX_HEADER_EXTRA: \usetikzlibrary{decorations.pathmorphing}
#+LATEX_HEADER_EXTRA: \useinnertheme{rounded}
#+LATEX_HEADER_EXTRA: \usetheme[section,navigation,pagenum,ddc]{tud}
#+LATEX_HEADER_EXTRA: %\usetheme{Boadilla}
#+LATEX_HEADER_EXTRA: %\usecolortheme{tud}
#+LATEX_HEADER_EXTRA: \institut{Institut f\"ur Algebra}%
#+LATEX_HEADER_EXTRA: \DeclareMathOperator\Orb{Orb}%
#+LATEX_HEADER_EXTRA: \title[TUD-CD mit \LaTeX\ gesetzt]{Beamer-Präsentationen mit dem CD der TU Dresden}
#+LATEX_HEADER_EXTRA: \AtBeginDocument{\date{22.\,6.~2016}}
#+LATEX_HEADER_EXTRA: \subtitle{TUD-CD mit \LaTeX\ gesetzt}
#+LATEX_HEADER_EXTRA: \setbeamerfont{description item}{series=\bfseries}
#+LATEX_HEADER_EXTRA: \setbeamertemplate{date/place in footline}[default][T. Schlemmer]
#+LATEX_HEADER_EXTRA: \setbeamertemplate{page number in footline}[frame][total]
#+LATEX_HEADER_EXTRA: \AtBeginSection[]{\begin{frame}<beamer>[allowframebreaks]\frametitle{Abschnitt}\footnotesize\tableofcontents[currentsection]\end{frame}}
#+LATEX_HEADER_EXTRA: \setlength{\tudbeamerfooterplacewidth}{0.3\linewidth}%
#+LATEX_HEADER_EXTRA: \setlength{\tudbeamerfooterpagenumwidth}{5em}%
#+LATEX_HEADER_EXTRA: \makeatletter
#+LATEX_HEADER_EXTRA: %\setlength{\tudbeamerfootertitlewidth}{\paperwidth-\beamer@leftmargin-\beamer@rightmargin
#+LATEX_HEADER_EXTRA: %   -\tudbeamerfooterplacewidth-\tudbeamerfooterpagenumwidth}%
#+LATEX_HEADER_EXTRA: \makeatother
#+COLUMNS: %45ITEM %10BEAMER_env(Env) %10BEAMER_envargs(Env Args) %4BEAMER_col(Col) %8BEAMER_extra(Extra)
#+PROPERTY: BEAMER_col_ALL 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.0 :ETC
#+LANGUAGE: de
* Einführung
** Allgemeines
*** Geschichte
- Corporate Design der TU Dresden
- tudbeamer Klasse (mit vielen Nachteilen)
- tud-cd-Paket
- \alert{Konfigurierbarer Beamer-Stil}
*** CD-Vorgaben (Handbuch)
- \textcolor{HKS65K100}{Ränder relativ zu Papiergrüße}
- \textcolor{red}{Schriften in MS Punkt (inkompatible Maßeinheit)}
- \textcolor{red}{Logoposition fehlt}
*** Designkriterien
- Interpretation der Vorgaben
- Abweichend: HKS Farbschema und Univers
- Kombinierbar mit @@latex:\textbackslash useinnertheme\{rounded\}@@
- Farbschema mit anderem Layout kombinierbar (partiell implementiert)
- Alle Stile überschreibbar
** Benutzung
*** Beispieldokument                                              :B_example:
:PROPERTIES:
:BEAMER_env: example
:END:
\textbackslash usepackage[ngerman]{babel}\\
\textbackslash usetheme[section,navigation]{tud}\\
\textbackslash institut{Institut f\textbackslash ''ur Algebra}%\\
\textbackslash title[Beispiel]{Langer Titel mit Beispiel}\\
\textbackslash begin{document}\\
\textbackslash maketitle\\
\textbackslash begin{frame}{Eine Folie}\\
Inhalt\\
\textbackslash end{frame}\\
\textbackslash end{document}\\

* Einstellungen
** @@latex:\textbackslash usetheme\{tud\}@@
*** Paketoptionen (Schriften)
- noeulermath :: Benutze keine Euler-Mathematikschriften
- noDIN :: Titel ohne DIN bold
- serifmath :: Nutze Computer Modern für Mathematik
- heavyfont :: Nutze Univers 55 statt Univers 45
- beamerfont :: Keine Fontänderungen
*** Paketoptionen (Seitenstruktur)
- noheader :: Benutze Folien ohne Kopfzeile
- smallrightmargin :: Schmaler rechter Rand (verletzt CD-Richtlinie
- pagenum :: Seitenzahlen in der Fußzeile anzeigen
- section :: mit Abschnittstitel auf jeder Folie
- navbar :: mit Navigationshilfen
- noddc :: ohne DRESDEN"=concept-Logo
- ddc :: mit DRESDEN"=concept-Logo
- ddcfooter :: mit DRESDEN"=concept Logo im Fußbereich (Standardeinstellung)
** @@latex:\textbackslash useoutertheme\{tud\}@@
*** Paketoptionen (@@latex:\textbackslash useoutertheme\{tud\}@@)
- noheader :: Benutze Folien ohne Kopfzeile
- smallrightmargin :: Schmaler rechter Rand (verletzt CD-Richtlinie
- pagenum :: Seitenzahlen in der Fußzeile anzeigen
- section :: mit Abschnittstitel auf jeder Folie
- navbar :: mit Navigationshilfen
- noddc :: ohne DRESDEN"=concept-Logo
- ddc :: mit DRESDEN"=concept-Logo
- ddcfooter :: mit DRESDEN"=concept Logo im Fußbereich (Standardeinstellung)
*** Makros (@@latex:\textbackslash useoutertheme\{tud\}@@)
- \textbackslash einrichtung{/einrichtung/} :: Legt die
 Einrichtung/Fakultät fest
- \textbackslash fachrichtung{/Fachrichtung/} :: Legt die
 Fachrichtung fest
- \textbackslash institut{/Institut/} :: Legt das
 Institut fest
- \textbackslash professur{/Professur/} :: Legt die
 Professur fest
- \textbackslash datecity{/Datumsort/} :: Legt den Ort für den Vortrag fest
*** Register (@@latex:\textbackslash useoutertheme\{tud\}@@)
- @@latex:\textbackslash topmarginnoheader@@ :: Länge, die den Oberen Rand Seitenrand bei
 Kopflosen Folien angibt.
- @@latex:\textbackslash tudbeamerfooterplacewidth@@ :: Länge, die Breite des
     Datums/Ort/(Autor-)Blockes in der Fußzeile bestimmt
- @@latex:\textbackslash tudbeamerfooterpagenumwidth@@ :: Länge, die Platz für
     die Seitenzahl in der Fußzeilereserviert
- @@latex:\textbackslash topmarginnoheader@@ :: Länge, die Platz für den
     Kurztitel in der Fußzeile reserviert
*** Vorlagen (@@latex:\textbackslash useoutertheme\{tud\}@@)      :B_frame:
:PROPERTIES:
:BEAMER_env: frame
:BEAMER_OPT: allowframebreaks
:END:
Vorlangen werden mit 
#+LaTeX: \textbf{\textbackslash setbeamertemplate\{\emph{Kategorie}\}[\emph{Vorlage}]} 
gesetzt. Es können neue
definiert und ausgewählt werden. Weitere Informationen dazu gibt es im
„Beamer User Guide“ (\texttt{texdoc beamer}).
**** headline                                                       :B_block:
:PROPERTIES:
:BEAMER_env: block
:END:
Vorlage für Seitenkopf
- tud titlepage :: Titelseitenkopf
- tud header :: normaler Folienkopf
- tud noheader :: Folienkopf für kopflose Folien

**** zweitlogo/titlepage                                            :B_block:
:PROPERTIES:
:BEAMER_env: block
:END:
Vorlage für ein zweites Logo im Kopf der Titelseite
- default :: kein Zweitlogo
- ddc :: DRESDEN"=concept-Logo
- logofile :: Eine Logo-Datei wird als Parameter übergeben und mit
              @@latex:\textbackslash includegraphics@@ eingebunden und auf die
              richtige Höhe skaliert.
Beispiel: 
#+LaTeX: \textbf{\textbackslash \mbox{setbeamertemplate} \{zweitlogo/headline\}[logofile]\{fremdfirma.png\}} 
**** zweitlogo/titlepage (Fortsetzung)                           :B_block:
:PROPERTIES:
:BEAMER_env: block
:END:
- freeform :: Es wird der \LaTeX -Code direkt als Parameter übergeben. Beispiel:
              #+LaTeX: \textbf{\textbackslash \mbox{setbeamertemplate} \{zweitlogo/headline\}[freeform]\{\textbackslash LaTeX\}} 
              In diesem Fall ist die Höhe des Logos im Makro
              @@latex:\texttt{\textbackslash logoheight}@@ hinterlegt. Für die
              Weiterverarbeitung ist wichtig, dass es in ein
              skaliertes Register expandiert wird (siehe
              @@latex:\texttt{beamerouterthemetod.sty}@@).

**** zweitlogo/headline                                             :B_block:
:PROPERTIES:
:BEAMER_env: block
:END:
Vorlage für ein zweites Logo im Kopf einer normalen Seite (keine Titelseite)
- default :: kein Zweitlogo
- ddc :: DRESDEN"=concept-Logo
- logofile :: Eine Logo-Datei wird als Parameter übergeben und mit
              @@latex:\textbackslash includegraphics@@ eingebunden und auf die
              richtige Höhe skaliert.
Beispiel: 
#+LaTeX: \textbf{\textbackslash setbeamertemplate\{zweitlogo/headline\}[logofile]\{fremdfirma.png\}} 
**** zweitlogo/headline (Fortsetzung)                            :B_block:
:PROPERTIES:
:BEAMER_env: block
:END:
- freeform :: Es wird der \LaTeX -Code direkt als Parameter übergeben. Beispiel:
              #+LaTeX: \textbf{\textbackslash setbeamertemplate\{zweitlogo/headline\}[freeform]\{\textbackslash LaTeX\}} 
              In diesem Fall ist die Höhe des Logos im Makro
              @@latex:\texttt{\textbackslash logoheight}@@ hinterlegt. Für die
              Weiterverarbeitung ist wichtig, dass es in ein
              skaliertes Register expandiert wird (siehe
              @@latex:\texttt{beamerouterthemetod.sty}@@).

**** date/place in footline                                      :B_block:
:PROPERTIES:
:BEAMER_env: block
:END:

- default :: Vorlage für Datum/Ort in Fußzeile mit optionalem Argument
 für Ort. Standardwert „TU Dresden“.

**** short title in footline                                     :B_block:
:PROPERTIES:
:BEAMER_env: block
:END:

- default :: Fügt den Kurztitel in die Fußzeile ein

**** page number in footline                                     :B_block:
:PROPERTIES:
:BEAMER_env: block
:END:
\small
- page :: Setzt die Seitenzahl. Die Form kann als optionaler Parameter
 übergeben werden. Standardwert „text and total". Für weitere Werte
 siehe unten, Vorlagen, die mit „page number: “ anfangen (dieser Teil
 wird automatisch hinzugefügt).
- frame :: Setzt die Foliennummer. Die Form kann als optionaler Parameter
 übergeben werden. Standardwert „text and total". Für weitere Werte
 siehe unten, Vorlagen, die mit „frame number: “ anfangen (dieser Teil
 wird automatisch hinzugefügt).

**** page number: text and total                                 :B_block:
:PROPERTIES:
:BEAMER_env: block
:END:
Setzt Seitenzahl – Sprachauswahl für Nummer und Gesamtzahl.(wird automatisch gesetzt)
- english :: Englisch
- german :: Deutsch

**** page number: text                                 :B_block:
:PROPERTIES:
:BEAMER_env: block
:END:
Setzt Seitenzahl – Sprachauswahl für Nummer.(wird automatisch gesetzt)
- english :: Englisch
- german :: Deutsch

**** page number: total                                             :B_block:
:PROPERTIES:
:BEAMER_env: block
:END:
Setzt Seitenzahl und Gesamtzahl ohne Worte.(wird automatisch gesetzt)
- default :: Standardeinstellung

**** page number: only                                              :B_block:
:PROPERTIES:
:BEAMER_env: block
:END:
Setzt Seitenzahl ohne Gesamtzahl ohne Worte.(wird automatisch gesetzt)
- default :: Standardeinstellung

**** frame number: text and total                                   :B_block:
:PROPERTIES:
:BEAMER_env: block
:END:
Setzt Foliennummer – Sprachauswahl für Nummer und Gesamtzahl.(wird automatisch gesetzt)
- english :: Englisch
- german :: Deutsch

**** frame number: text                                   :B_block:
:PROPERTIES:
:BEAMER_env: block
:END:
Setzt Foliennummer – Sprachauswahl für Nummer.(wird automatisch gesetzt)
- english :: Englisch
- german :: Deutsch

**** frame number: total                                            :B_block:
:PROPERTIES:
:BEAMER_env: block
:END:
Setzt Foliennummer und Gesamtzahl ohne Worte.(wird automatisch gesetzt)
- default :: Standardeinstellung

**** frame number: only                                             :B_block:
:PROPERTIES:
:BEAMER_env: block
:END:
Setzt Foliennummer ohne  Gesamtzahl ohne Worte.(wird automatisch gesetzt)
- default :: Standardeinstellung


**** footline                                                       :B_block:
:PROPERTIES:
:BEAMER_env: block
:END:
Setzt den Seitenfuß

- tud titlepage :: Fußzeile auf der Titelseite
- tud pagenum :: Fußzeile mit Seiten- oder Folienzahl entsprechend dem
   Parameter zu „page number in footline“
- tud nopagenum :: Fußzeile ohne Seiten- und Folienzahl

**** frametitle                                                  :B_block:
:PROPERTIES:
:BEAMER_env: block
:END:
Setzt den Folientitel
- tud titlesection :: Setzt vor dem eigentlichen Titel den
Abschnittstitel
- tud notitlesection :: Es wird nur der 

**** einrichtung/titlepage                                          :B_block:
:PROPERTIES:
:BEAMER_env: block
:END:
Setzt die Einrichtung im Seitenkopf auf der Titelseite

- default :: normal
- empty :: keine Ausgabe
**** fachrichtung/titlepage                                         :B_block:
:PROPERTIES:
:BEAMER_env: block
:END:
Setzt die Fachrichtung im Seitenkopf auf der Titelseite

- default :: normal
- empty :: keine Ausgabe
**** intstitut/titlepage                                            :B_block:
:PROPERTIES:
:BEAMER_env: block
:END:
Setzt den Institutsnamen im Seitenkopf auf der Titelseite

- default :: normal
- empty :: keine Ausgabe

**** professur/titlepage                                            :B_block:
:PROPERTIES:
:BEAMER_env: block
:END:
Setzt die Professur im Seitenkopf auf der Titelseite

- default :: normal
- empty :: keine Ausgabe

*** Beispiel (@@latex:\textbackslash useoutertheme\{tud\}@@)

\textbackslash setbeamercolor{normal text}{bg=white}\\
\textbackslash setbeamertemplate{headline}[tud header]\\
\textbackslash setbeamertemplate{footline}[tud pagenum]\\
\textbackslash setbeamertemplate{frametitle}[tud notitlesection]\\
 

** @@latex:\textbackslash usefonttheme\{tud\}@@

*** Paketoptionen (@@latex:\textbackslash usefonttheme\{tud\}@@)
- noeulermath :: Benutze keine Euler-Mathematikschriften
- noDIN :: Titel ohne DIN bold
- nodin :: Titel ohne DIN bold
- serifmath :: Nutze Computer Modern für Mathematik
- heavyfont :: Nutze Univers 55 statt Univers 45
- beamerfont :: Keine Fontänderungen

*** Makros (@@latex:\textbackslash usefonttheme\{tud\}@@)
- @@latex:\textbackslash tudtitlenormalsize@@ :: Ersatz für @@latex:\textbackslash
  normalsize@@ auf der Titelseite
- @@latex:\textbackslash tudtitlesmall@@ :: Ersatz für @@latex:\textbackslash small@@ auf der Titelseite
- @@latex:\textbackslash tudtitletiny@@ :: Ersatz für @@latex:\textbackslash tiny@@ auf der Titelseite

Darüberhinaus lädt dieses Paket das Paket „tudfonts“ mit all seinen makros

*** Schriftvorlagen (@@latex:\textbackslash usefonttheme\{tud\}@@) :B_frame:
:PROPERTIES:
:BEAMER_env: frame
:BEAMER_OPT: allowframebreaks
:END:
Vorlangen werden mit \textbackslash
setbeamerfont{/Name/}{Werte} gesetzt. Sie können mit @@latex:\textbackslash
usebeamerfont@@ aktiviert werden. Weitere Informationen dazu gibt es im
„Beamer User Guide“ (@@latex:\texttt{texdoc beamer}@@).

Es werden folgende Vorlagen definiert:
-  @@latex:\textbackslash setbeamerfont\{itemize/enumerate subbody\} \{size=\textbackslash scriptsize\}@@
-  @@latex:\textbackslash setbeamerfont\{itemize/enumerate subsubbody\} \{size=\textbackslash scriptsize\}@@
-  @@latex:\textbackslash setbeamerfont\{section in head/foot\}\{size=\textbackslash normalsize, family=\textbackslash sffamily\}@@
-  @@latex:\textbackslash setbeamerfont\{frametitle\} \{size=\textbackslash normalsize, family=\textbackslash sffamily\}@@
-  @@latex:\textbackslash setbeamerfont\{framesubtitle\} \{size=\textbackslash
   small, series=\textbackslash bfseries,family=\textbackslash sffamily\}@@
-  @@latex:\textbackslash setbeamerfont\{footline\} \{size=\textbackslash tiny\}@@
-  @@latex:\textbackslash setbeamerfont\{block title\} \{size=\{\}\}@@
-  @@latex:\textbackslash if@noDIN
    \textbackslash setbeamerfont\{title\} \{size=\textbackslash
   @setfontsize\textbackslash LARGE\textbackslash @xviipt\{22\},
   series=\textbackslash bfseries, family=\textbackslash sffamily\}
  \textbackslash else
    \textbackslash setbeamerfont\{title\} \{size=\textbackslash
   @setfontsize\textbackslash LARGE\textbackslash @xviipt\{22\},
   series=\textbackslash bfseries, family=\textbackslash dinfamily\}
  \textbackslash fi@@
-  @@latex:\textbackslash setbeamerfont\{subtitle\} \{series=\textbackslash
   bfseries, family=\textbackslash sffamily\}@@
-  @@latex:\textbackslash setbeamerfont\{einrichtung/titlepage\}
   \{size=\textbackslash tudtitletiny, series=\textbackslash bfseries\}@@
-  @@latex:\textbackslash setbeamerfont\{fachrichtung/titlepage\} \{size=\textbackslash tudtitletiny\}@@
-  @@latex:\textbackslash setbeamerfont\{institut/titlepage\} \{parent=fachrichtung/titlepage\}@@
-  @@latex:\textbackslash setbeamerfont\{professur/titlepage\} \{parent=fachrichtung/titlepage\}@@
-  @@latex:\textbackslash setbeamerfont\{date in head/foot/titlepage\} \{size=\textbackslash tudtitlenormalsize\}@@
-  @@latex:\textbackslash setbeamerfont\{author\} \{size=\textbackslash tudtitlesmall\}@@



** @@latex:\textbackslash usecolortheme\{tud\}@@

*** Makros (@@latex:\textbackslash usecolortheme\{tud\}@@)
- @@latex:\textbackslash darktitlepage@@ :: Stellt eine dunkle Titelseite ein, wie
vom CD gefordert
- @@latex:\textbackslash whitetitlepage@@ :: Titelseite wird weiß (nicht CD-Konform).

Darüberhinaus lädt dieses Paket das Paket „tudcolors“ mit all seinen
makros und den HKS-Farben (siehe Dokumentation von tudmathposter)

*** Farbvorlagen (@@latex:\textbackslash usecolortheme\{tud\}@@)  :B_frame:
:PROPERTIES:
:BEAMER_env: frame
:BEAMER_OPT: allowframebreaks
:END:
Farbvorlagen werden mit \textbackslash
setbeamercolor{/Name/}{Werte} gesetzt. Sie können mit @@latex:\textbackslash
usebeamercolor@@ für die Aktivierung geladen werden. Weitere Informationen dazu gibt es im
„Beamer User Guide“ (@@latex:\texttt{texdoc beamer}@@).

Es werden folgende Vorlagen definiert:
-  @@latex:\textbackslash setbeamercolor\{normal text\} \{fg=HKS41K100,bg=white\}@@
-  @@latex:\textbackslash setbeamercolor\{structure\} \{fg=HKS41K100\}@@
-  @@latex:\textbackslash setbeamercolor\{alerted text\} \{fg=HKS44K100\}@@
-  @@latex:\textbackslash setbeamercolor\{alternate palette\} \{fg=HKS92K80\}@@
-  @@latex:\textbackslash setbeamercolor\{date in head/foot\} \{parent=alternate palette\}@@
-  @@latex:\textbackslash setbeamercolor\{title in head/foot\} \{parent=alternate palette\}@@
-  @@latex:\textbackslash setbeamercolor\{page number in head/foot\} \{parent=alternate palette\}@@
-  @@latex:\textbackslash setbeamercolor\{section in head/foot\} \{parent=alternate palette\}@@
-  @@latex:\textbackslash setbeamercolor\{subsection in head/foot\} \{parent=section in head/foot\}@@
-  @@latex:\textbackslash setbeamercolor\{upper separation line head\} \{parent=alternate palette\}@@
-  @@latex:\textbackslash setbeamercolor\{lower separation line head\} \{parent=upper separation line head\}@@
-  @@latex:\textbackslash setbeamercolor\{author in head/foot\} \{parent=section in head/foot\}@@
-  @@latex:\textbackslash setbeamercolor\{title in head/foot\} \{parent=subsection in head/foot\}@@
-  @@latex:\textbackslash setbeamercolor\{logo\} \{use=structure, fg=structure.fg\}@@
-  @@latex:\textbackslash newcommand*\{\textbackslash darktitlepage\}\{@@%
  -  @@latex:\textbackslash setbeamercolor\{normal text/titlepage\} \{fg=white,bg=HKS41K100\}%@@
  -  @@latex:\textbackslash setbeamercolor\{title\} \{use=normal text/titlepage, fg=normal text/titlepage.fg\}%@@
  -  @@latex:\textbackslash setbeamercolor\{subtitle\} \{use=normal
     text/titlepage, fg=normal text/titlepage.fg\}%@@
  -  @@latex:\textbackslash setbeamercolor\{author/titlepage\} \{use=normal
     text/titlepage, fg=normal text/titlepage.fg\}%@@
  -  @@latex:\textbackslash setbeamercolor\{headline/titlepage\} \{use=normal
     text/titlepage, fg=normal text/titlepage.fg\}%@@
  -  @@latex:\textbackslash setbeamercolor\{logo/titlepage\} \{use=normal
     text/titlepage, fg=normal text/titlepage.fg\}%@@
  -  @@latex:\textbackslash setbeamercolor\{einrichtung/titlepage\}
     \{use=normal text/titlepage, fg=normal text/titlepage.fg\}%@@
  -  @@latex:\textbackslash setbeamercolor\{fachrichtung/titlepage\}
     \{use=einrichtung/titlepage, fg=einrichtung/titlepage.fg\}%@@
  -  @@latex:\textbackslash setbeamercolor\{institut/titlepage\}
     \{use=einrichtung/titlepage, fg=einrichtung/titlepage.fg\}%@@
  -  @@latex:\textbackslash setbeamercolor\{professur/titlepage\}
     \{use=einrichtung/titlepage, fg=einrichtung/titlepage.fg\}%@@
  -  @@latex:\textbackslash setbeamercolor\{upper separation line
     head/titlepage\} \{use=normal text/titlepage, fg=normal text/titlepage.fg\}%@@
  -  @@latex:\textbackslash setbeamercolor\{lower separation line head/titlepage\}%
      \{use=upper separation line head/titlepage, fg=upper separation line head/titlepage.fg\}%@@
  -  @@latex:\textbackslash setbeamercolor\{date in head/foot/titlepage\}
     \{use=normal text/titlepage, fg=normal text/titlepage.fg\}%@@
  -  @@latex:\textbackslash let\textbackslash logo\@ DDC\textbackslash logo\@ DDC\@ white@@
  -  @@latex:\textbackslash let\textbackslash logo\@ DDCf\textbackslash logo\@ DDC\@ whitef
     \}@@
-  @@latex:\textbackslash newcommand*\{\textbackslash whitetitlepage\}\{%@@
  -   @@latex:\textbackslash setbeamercolor\{normal text/titlepage\}@@
      \{use=normal text,fg=normal text.fg, bg=normal text.bg\}@@
  - @@latex:\textbackslash setbeamercolor\{title\} \{use=normal
    text/titlepage, fg=normal text/titlepage.fg\}%@@
  -  @@latex:\textbackslash setbeamercolor\{subtitle\} \{use=normal
     text/titlepagexo, fg=normal text/titlepage.fg\}%@@
  -  @@latex:\textbackslash setbeamercolor\{author/titlepage\} \{use=normal
     text/titlepage, fg=normal text/titlepage.fg\}%@@
  -  @@latex:\textbackslash setbeamercolor\{headline/titlepage\} \{use=normal
     text/titlepage, fg=normal text/titlepage.fg\}%@@
  -  @@latex:\textbackslash setbeamercolor\{logo/titlepage\} \{use=normal
     text/titlepage, fg=normal text/titlepage.fg\}%@@
  -  @@latex:\textbackslash setbeamercolor\{einrichtung/titlepage\} \{fg=HKS92K100\}%@@
  -  @@latex:\textbackslash setbeamercolor\{fachrichtung/titlepage\}
     \{use=einrichtung/titlepage, fg=einrichtung/titlepage.fg\}%@@
  -  @@latex:\textbackslash setbeamercolor\{institut/titlepage\}
     \{use=einrichtung/titlepage, fg=einrichtung/titlepage.fg\}%@@
  -  @@latex:\textbackslash setbeamercolor\{professur/titlepage\}
     \{use=einrichtung/titlepage, fg=einrichtung/titlepage.fg\}%@@
  -  @@latex:\textbackslash setbeamercolor\{upper separation line
     head/titlepage\} \{fg=HKS92K100\}%@@
  -  @@latex:\textbackslash setbeamercolor\{lower separation line head/titlepage\}%
      \{use=upper separation line head/titlepage,fg=upper separation line
        head/titlepage.fg\}%@@
  -  @@latex:\textbackslash setbeamercolor\{date in head/foot/titlepage\} \{fg=HKS92K100\}%@@
  -  @@latex:\textbackslash let\textbackslash logo\@ DDC\textbackslash logo\@ DDC\@ bunt%@@
  -  @@latex:\textbackslash let\textbackslash logo\@ DDCf\textbackslash logo\@ DDC\@ colorf
     \}@@
-  @@latex:\textbackslash darktitlepage@@
  
-  @@latex:\textbackslash setbeamercolor\{block body\} \{use=normal text,
   fg=normal text.fg, bg=HKS41K10\}@@
-  @@latex:\textbackslash setbeamercolor\{block title\} \{fg=HKS41K100,bg=HKS41K20\}@@
-  @@latex:\textbackslash setbeamercolor\{block body example\} \{use=normal
   text, fg=normal text.fg, bg=HKS41K10\}@@
-  @@latex:\textbackslash setbeamercolor\{block title example\}
   \{fg=HKS57K100, bg=HKS41K20\}@@
-  @@latex:\textbackslash setbeamercolor\{block body alerted\} \{use=normal
   text, fg=normal text.fg, bg=HKS65K10\}@@
-  @@latex:\textbackslash setbeamercolor\{block title alerted\}
   \{fg=HKS07K100, bg=HKS65K20\}@@



** @@latex:\textbackslash useinnertheme\{tud\}@@

*** Vorlagen (@@latex:\textbackslash useinnertheme\{tud\}@@)      :B_frame:
:PROPERTIES:
:BEAMER_env: frame
:BEAMER_OPT: allowframebreaks
:END:
Für die inneren Vorlagen gibt es keine Vorgaben außer für die
Titelseite.
**** Verwendete Vorlagen/Makros                                  :B_block:
:PROPERTIES:
:BEAMER_env: block
:END:
- @@latex:\textbackslash beamertemplatedotitem@@ :: siehe beamer-Dokumentation
- @@latex:\textbackslash usesubitemizeitemtemplate\{-\/-\}@@ :: siehe
     beamer-Dokumentation
- @@latex:\textbackslash setbeamertemplate\{title page\}[tud]@@ :: stellt das CD
     der TUD für die Titelseite ein. Dieses Makro wird automatisch mit
     @@latex:\textbackslash begin \{document\}@@ aufgerufen.

* Tips und Tricks
** Tips
*** Fußzeile
Die Fußzeile sollte die wichtigsten Informationen enthalten, an die
sich das Publikum erinnern soll. Wenn das TU-Logo im Kopf enthalten
ist die Angabe „TU Dresden“ redundant.

@@latex:\textbackslash setbeamertemplate\{date/place in
footline\}[default][I. Nachname]@@

Setzt statt der TU Dresden den Namen
des Sprechers.
*** Blöcke mit runden Ecken und Schatten
**** Aufruf                                                      :B_block:
:PROPERTIES:
:BEAMER_env: block
:END:
Blöcke wie dieser hier werden mittels 

@@latex:\textbackslash useinnertheme[shadow=true]\{rounded\}@@

in der Dokumentpräambel voreingestellt
** Ein Beispiel    
*** Eine Beispielfolie                                              
**** 0.3                                                       :B_columns:
:PROPERTIES:
:BEAMER_env: columns
:END:
***** 0.3                                                      :B_column:
:PROPERTIES:
:BEAMER_env: column
:BEAMER_col: 0.3
:END:
#+BEGIN_EXPORT latex
  \tikzstyle{automorphismuspfeil}=[->,HKS44K100,decoration={bent,aspect=0.3,amplitude=3},decorate]
  \tikzstyle{automorphismuspfeil2}=[automorphismuspfeil,decoration={bent,aspect=0.3,amplitude=2}]
  \begin{tikzpicture}
  \draw (0,0) node (n0) {0};
  \draw (-1,1) node (n1) {1};
  \draw (1,1) node (n2) {2};
  \draw (-1.5,2) node (n3) {3};
  \draw (-0.5,2) node (n4) {4};
  \draw (0.5,2) node (n5) {5};
  \draw (1.5,2) node (n6) {6};
  \draw (0,3) node (n7) {7};
  \draw (n0) -- (n1) -- (n3) -- (n7) -- (n6) -- (n2) -- (n0);
  \draw (n1) -- (n4) -- (n7) -- (n5) -- (n2);
  \only<1,2,5,6> {
    \draw[automorphismuspfeil] (n1) -- (n2);
    \draw[automorphismuspfeil] (n2) -- (n1); 
  }
  \only<3,4>{
    \draw[automorphismuspfeil] (n3) -- (n4);
    \draw[automorphismuspfeil] (n4) -- (n3);
  }
  \only<5>{
    \draw[automorphismuspfeil] (n3) -- (n5);
    \draw[automorphismuspfeil] (n5) -- (n3);
  }
  \only<6>{
    \draw[automorphismuspfeil] (n3) -- (n6);
    \draw[automorphismuspfeil] (n6) -- (n3);
  }
  \only<6>{
    \draw[automorphismuspfeil2] (n4) -- (n5);
    \draw[automorphismuspfeil2] (n5) -- (n4);
  }
  \only<5>{
    \draw[automorphismuspfeil] (n4) -- (n6);
    \draw[automorphismuspfeil] (n6) -- (n4);
  }
  \only<3,4>{
    \draw[automorphismuspfeil] (n5) -- (n6);
    \draw[automorphismuspfeil] (n6) -- (n5);
  }
  \only<1>{
    \draw[automorphismuspfeil] (n3) -- (n5);
    \draw[automorphismuspfeil2] (n5) -- (n4);
    \draw[automorphismuspfeil] (n4) -- (n6);
    \draw[automorphismuspfeil] (n6) -- (n3);
  }
  \only<2>{
    \draw[automorphismuspfeil] (n3) -- (n6);
    \draw[automorphismuspfeil] (n6) -- (n4);
    \draw[automorphismuspfeil2] (n4) -- (n5);
    \draw[automorphismuspfeil] (n5) -- (n3);
  }
  \end{tikzpicture}
  
#+END_EXPORT
***** Beschreibung                                        :B_block:BMCOL:
:PROPERTIES:
:BEAMER_env: block
:BEAMER_OPT: c
:BEAMER_cat: <1-7>
:BEAMER_col: 0.7
:END:

Eine Tabelle

#+BEAMER: {}\uncover<2->{\tiny %}
|------------------+-----+-----+-----+-----+-----+-----+-----+-----|
|                  | $1$ | $a$ | $b$ | $c$ | $d$ | $e$ | $f$ | $g$ |
|------------------+-----+-----+-----+-----+-----+-----+-----+-----|
| $1=(1)$          | $1$ | $a$ | $b$ | $c$ | $d$ | $e$ | $f$ | $g$ |
| $a=(34)$         | $a$ | $1$ | $c$ | $b$ | $g$ | $f$ | $e$ | $d$ |
| $b=(56)$         | $b$ | $c$ | $1$ | $a$ | $f$ | $g$ | $d$ | $e$ |
| $c=(34)(56)$     | $c$ | $b$ | $a$ | $1$ | $e$ | $d$ | $g$ | $f$ |
| $d=(12)(35)(46)$ | $d$ | $f$ | $g$ | $e$ | $1$ | $c$ | $a$ | $b$ |
| $e=(12)(36)(45)$ | $e$ | $g$ | $f$ | $d$ | $c$ | $1$ | $b$ | $a$ |
| $f=(12)(3546)$   | $f$ | $d$ | $e$ | $g$ | $b$ | $a$ | $c$ | $1$ |
| $g=(12)(3645)$   | $g$ | $e$ | $d$ | $f$ | $a$ | $b$ | $1$ | $c$ |
|------------------+-----+-----+-----+-----+-----+-----+-----+-----|
#+BEAMER: }


* Minimal agierende Automorphismen
** Quasiordnung der Automorphismen
*** Ein Satz mit Beweis
**** Quasiordnung                                              :B_theorem:
:PROPERTIES:
:BEAMER_env: theorem
:BEAMER_OPT: <1->
:END:
Sei $G\leq \mathfrak{Aut}(M,\leq)$ eine Untergruppe der geordneten
Menge $(M,\leq)$. Dann ist die Relation ${\sqsubseteq}\subseteq
G\times G$ mit 
\[
g\sqsubseteq h :\Leftrightarrow ∀u∈\Orb(〈g〉)∃U'∈\Orb(〈h〉)\text{ und }U\subseteq U'
\]
eine Quasiordnung.

**** Beweis                                              :B_ignoreheading:
:PROPERTIES:
:BEAMER_env: proof
:BEAMER_OPT: <1>
:END:
1. Reflexiv: $\Orb(〈g〉) = \Orb(〈g〉)$
2. Transitiv: 
#+BEGIN_EXPORT latex
\dots
#+END_EXPORT
*** Beispielfolie                                               :B_example:
:PROPERTIES:
:BEAMER_env: example
:END:
**** Beispieltitel                                             :B_example:
:PROPERTIES:
:BEAMER_env: example
:END:
 mal sehen, was wird
**** Block hervorgehoben                                    :B_alertblock:
:PROPERTIES:
:BEAMER_env: alertblock
:END:
Inhalt


# Local Variables:
# org-beamer-outline-frame-title: "Inhalt"
# org-beamer-outline-frame-options: "allowframebreaks"
# End:
