#!/bin/bash
selfname="$0"
basedir=$(dirname "$0")/../../..
datadir="$basedir/doc/latex/tud-beamerstyle"

TEXMFDBS="`kpsexpand \$TEXMFDBS | sed s/{/{$datadir/`"
export TEXMFDBS

cd "$datadir"
pdflatex beamer-org-mode-demo.tex
pdflatex beamer-org-mode-demo.tex
pdflatex beamer-org-mode-demo.tex
latex beamer-org-mode-demo.tex
dvicopy beamer-org-mode-demo.dvi beamer-org-mode-demo-nonvf.dvi
dvips -u +tudscr.map -u +tud.map -u +univers.map -u +dinbold.map beamer-org-mode-demo-nonvf
ps2pdf beamer-org-mode-demo-nonvf.ps
